# SwissRe Non-Production Configuration

# Backend configuration
backend:
  enabled: true
  replicaCount: 1
  
  image:
    repository: trialf20tqh.jfrog.io/docker-trial/swissre-api
    tag: "latest"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  
  env:
    - name: AWS_REGION
      value: "us-east-1"
    - name: SWISSRE_SECRET_NAME
      value: "swissre/api-token"
    - name: LOG_LEVEL
      value: "DEBUG"

# Frontend configuration
frontend:
  enabled: true
  replicaCount: 1
  
  image:
    repository: trialf20tqh.jfrog.io/docker-trial/swissre-streamlit
    tag: "latest"
    pullPolicy: IfNotPresent
  
  service:
    type: NodePort
    port: 8501
    targetPort: 8501
  
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  
  env:
    - name: SWISSRE_API_URL
      value: "http://swissre-nonprod-backend:8080"

# Service Account
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::352635226587:role/SFGAppSwissReServiceRole"
  name: "swissre-service-account"

# Security Context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
  capabilities:
    drop:
    - ALL
