# SwissRe Non-Production Configuration

# Backend configuration
backend:
  enabled: true
  replicaCount: 1
  
  image:
    repository: python
    tag: "3.11-slim"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  env:
    - name: ENVIRONMENT
      value: "nonprod"
    - name: LOG_LEVEL
      value: "INFO"

# Frontend configuration
frontend:
  enabled: true
  replicaCount: 1
  
  image:
    repository: python
    tag: "3.11-slim"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8501
    targetPort: 8501
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  env:
    - name: ENVIRONMENT
      value: "nonprod"
    - name: BACKEND_URL
      value: "http://swissre-nonprod-swissre-microservice-backend:8080"

# Service Account
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::352635226587:role/AgenticAIServiceRole
  name: "swissre-service-account"

# Security Context
podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Ingress
ingress:
  enabled: false
