name: CI Helm Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'
    
    - name: Helm lint
      run: |
        helm lint ./helm
    
    - name: Helm template dry-run
      run: |
        helm template swissre-test ./helm \
          --values ./helm/values-nonprod.yaml \
          --dry-run
